name: 'rust-toolchain'
description: 'Install the Rust toolchain'
author: 'actions-rs team'
branding:
  icon: play-circle
  color: black
inputs:
  toolchain:
    description: |
      Rust toolchain name.

      See https://github.com/rust-lang/rustup.rs#toolchain-specification
    required: false
  target:
    description: Target triple to install for this toolchain
    required: false
  default:
    description: Set installed toolchain as default
    default: false
  override:
    description: Set installed toolchain as an override for a directory
    default: false
  profile:
    description: Name of the group of components to be installed for a new toolchain
    required: false
  components:
    description: Comma-separated list of components to be additionally installed for a new toolchain
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
